apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: py6app
  name: py6app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py6app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: py6app
    spec:
      containers:
      - image: aumthakkar/py6app:v1
        name: py6app
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: py6app
  name: py6app
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: py6app

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: py6app
spec:
  ingressClassName: nginx
  rules:
  - host: "python-app.test.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: py6app 
            port:
              number: 5000
